
spring:
   liquibase:
     enabled: true
     change-log: classpath:/db/changelog/db.changelog-master.yaml
   application:
    name: accounts-ms
   datasource:
    url: jdbc:postgresql://dev-postgres-01.unibank.lan/postgres?currentSchema=test_schema
    username: postgres
    password: A123456a
   jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database: postgresql
        database-platform : org.hibernate.dialect.PostgreSQLDialect
